---
abstract: 'Fast, simple message matching'
author:
  - ', 2013 Dana M. Diederich. All Rights Reserved.'
  - 'Dana M. Diederich <diederich@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
  Module::Install: 0
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: artistic2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Message-Match
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.6.0
resources:
  bugtracker: https://github.com/dana/perl-Message-Match/issues
  homepage: https://metacpan.org/module/Message::Match
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: git://github.com/dana/perl-Message-Match.git
version: 0.4
